import { useEffect, useMemo } from "react";
import { useDispatch, useSelector } from "react-redux";
import {
  Users,
  ClipboardList,
  CalendarClock,
  Sparkles,
} from "lucide-react";

import StatCard from "../components/ui/dashboard/StatCard";
import RecentInteractions from "../components/ui/dashboard/RecentInteraction";
import {
  fetchInteractions,
  selectAllInteractions,
  selectHistoryStatus,
} from "../store/slices/historySlice";

export default function Dashboard() {
  const dispatch = useDispatch();
  const interactions = useSelector(selectAllInteractions);
  const status = useSelector(selectHistoryStatus);

  useEffect(() => {
    dispatch(fetchInteractions());
  }, [dispatch]);

  const stats = useMemo(() => {
    const activeHcps = new Set(
      interactions.map((i) => i.hcp_name).filter(Boolean)
    );
    const pendingFollowUps = interactions.filter((i) => i.follow_up).length;
    const withAiSummary = interactions.filter((i) => i.ai_summary).length;

    return {
      total: interactions.length,
      activeHcps: activeHcps.size,
      pendingFollowUps,
      withAiSummary,
    };
  }, [interactions]);

  const insightHighlights = useMemo(() => {
    if (interactions.length === 0) return [];

    const positive = interactions.filter((i) => i.sentiment === "Positive");
    const highlights = [];

    if (positive.length > 0) {
      highlights.push(
        `📈 ${positive.length} of ${interactions.length} logged interactions show positive HCP sentiment.`
      );
    }
    if (stats.pendingFollowUps > 0) {
      highlights.push(
        `✅ ${stats.pendingFollowUps} interaction(s) have an open follow-up action.`
      );
    }
    const mostRecentPositive = positive[0];
    if (mostRecentPositive) {
      highlights.push(
        `💡 ${mostRecentPositive.hcp_name} is showing positive sentiment.`
      );
    }

    return highlights;
  }, [interactions, stats.pendingFollowUps]);

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold">Dashboard</h1>

        <p className="text-slate-500 mt-2">
          Welcome back! Here's your healthcare CRM overview.
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 xl:grid-cols-4">
        <StatCard
          title="Total Interactions"
          value={status === "loading" ? "—" : stats.total}
          subtitle="Logged to date"
          icon={ClipboardList}
        />

        <StatCard
          title="Active HCPs"
          value={status === "loading" ? "—" : stats.activeHcps}
          subtitle="Unique HCPs engaged"
          icon={Users}
        />

        <StatCard
          title="Pending Follow-ups"
          value={status === "loading" ? "—" : stats.pendingFollowUps}
          subtitle="Awaiting action"
          icon={CalendarClock}
        />

        <StatCard
          title="AI Summaries"
          value={status === "loading" ? "—" : stats.withAiSummary}
          subtitle="Generated by AI"
          icon={Sparkles}
        />
      </div>

      {/* Bottom Section */}
      <div className="grid grid-cols-1 gap-6 xl:grid-cols-3">
        <div className="xl:col-span-2">
          <RecentInteractions interactions={interactions} />
        </div>

        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6">
          <h2 className="text-xl font-semibold mb-4">AI Insights</h2>

          <div className="space-y-4">
            {insightHighlights.length > 0 ? (
              insightHighlights.map((line) => (
                <div key={line} className="p-4 rounded-xl bg-blue-50">
                  {line}
                </div>
              ))
            ) : (
              <p className="text-sm text-slate-500">
                Log a few interactions to see AI-generated highlights here.
              </p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
